max_name_length: 50
max_email_length: 256
min_password_length: 6
gravatar_size: 80
default_gravatar_size: 50
items_per_page: 10
time_reset_password: 2
content_max_length: 140
image_max_size_mb: 5
allowed_image_content_types: ["image/jpeg", "image/gif", "image/png"]
allowed_image_content: "image/jpeg,image/gif,image/png"
image_resize_to_limit: [500, 500]
